version: "2"

run:
  timeout: 3m
  relative-path-mode: gomod
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0